<form class="form-login" action="/registrar" method="post">
	<div class="">
		<input class="input-texto form-control" type="text" name="nome"  placeholder="Nome">
		<input class="input-texto form-control" type="email" name="email"  placeholder="E-mail">
		<input class="input-senha form-control" type="password" name="senha" placeholder="Senha">
		<button class="input-submit"  type="submit" >Cadastrar</button>
	</div>
	<?php if ($this->view->login == 'error') { ?>
		<span class="text text-danger" >Email e ou senha invalido(s)</span>
	<?php } ?>
</form>