<div class="container">
    <div class="card text-center mt-5">
    <div class="card-header p-4">
    
    </div>
    <div class="card-body">
        <p><?php echo $this->$view->pessoa['nome']?></p>
        <p><?php echo $this->$view->pessoa['cpf']?></p>
        <p><?php echo $this->$view->pessoa['rg']?></p>
        <p><?php echo $this->$view->pessoa['data_nascimento']?></p>
        <p><?php echo $this->$view->pessoa['data_cadastro']?></p>
        <p><?php echo $this->$view->pessoa['telefone']?></p>
        <p><?php echo $this->$view->pessoa['endereco']?></p>
        <p><?php echo $this->$view->pessoa['numero']?></p>
        <p><?php echo $this->$view->pessoa['cep']?></p>
        <p><?php echo $this->$view->pessoa['uf']?></p>

    </div>
    <div class="card-footer text-muted">
        
    </div>
    </div>  
</div>