<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container">
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="navbar-brand" href="/create">Novo</a>
				</li>
				<li class="nav-item">
					<a class="navbar-brand" href="/pessoa">Home</a>
				</li>
				<li class="nav-item">
					<a class="navbar-brand mr-5" href="/sair">Sair</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<div class="container mt-5 aline-center">
	
	<table class="table table-striped">
		<thead> 
				<tr>
				<th scope="col">#</th>
				<th scope="col">Nome</th>
				<th scope="col">CPF</th>
				<th scope="col">RG</th>	
				<th scope="col">Data de Nascimento</th>
				<th scope="col">Data de Cadastro</th>
				<th></th>
				<th>Ação</th>
				<th></th>
				</tr> 
		</thead>
		<tbody>
			<?php foreach ($this->view->pessoas as  $pessoa) { ?>
				<tr>
					<td><?php echo($pessoa['id']);?></td>	
					<td><?php echo($pessoa['nome']);?></td>
					<td><?php echo($pessoa['cpf']);?></td>
					<td><?php echo($pessoa['rg']);?></td>
					<td><?php echo(date('d/m/Y',strtotime($pessoa['data_nascimento'])));?></td>
					<td><?php echo(date('d/m/Y H:m:s',strtotime($pessoa['data_cadastro'])));?>
					<td><a href="/detalhe?id=<?=$pessoa['id']?>" class="btn btn-primary btn-sm">Exibir</a></td>
					<td><a href="/edit?id=<?=$pessoa['id']?>" class="btn btn-success btn-sm">Editar</a></td>
					<td><a href="/destroy?id=<?=$pessoa['id']?>" class="btn btn-danger btn-sm">Excluir</a></td>
				</td>
			</tr>
			<?php } ?>
		</tbody>
	</table>
</div>

			
